### ISSUE TITLE
Problem with Overleaf import

### ISSUE THREAD

**Issue by riccardosoro** [NiccoMlt/Unibo-Tesi-Template#15]
When i try to compile on Overleaf it generates this error:

Package frontespizio Warning: Missing file output-frn.pdf.

**Comment by NiccoMlt** [comment]
Probably is due to `frontespizio` package.

In a supported environment, `arara` is preferred because it supports a dedicated rule to compile frontspiece LaTeX file which is generated by `frontespizio` package at first invocation of `lualatex`, so following invocation can have the PDF file available.

You can try generating your `output-frn.tex` locally compiling the document with `arara`, and then upload `output-frn.pdf` onto Overleaf; this should work without further modifications.

If you can't generate the PDF file locally, you can upload a frontspiece LaTeX file and include it like a normal source in the main document.

The package generates a file like this:
```latex
%% This file has been automatically generated by `frontespizio'.
%% Don't use it as a model for a new frontispiece, use the
%% `frontespizio' environment in you document instead.
\documentclass [titlepage]{article}
\usepackage [a4paper,left=1cm,bottom=1.5cm,right=1cm,top=1cm]{geometry}
\usepackage [luatex]{graphicx}
\usepackage [luatex,svgnames]{xcolor}
\usepackage[nowrite,infront,standard,nouppercase]{frontespizio}
\nofiles 
\fontoptionnormal 

\usepackage {fontspec}
\setmainfont [Ligatures=TeX]{Latin Modern Roman}

\Universita {Bologna}
\Istituzione {Alma Mater Studiorum --- Università di Bologna \\Campus di Cesena}
\Divisione {Dipartimento di Informatica --- Scienza e Ingegneria}
\Corso [Laurea magistrale]{Ingegneria e Scienze Informatiche}
\Annoaccademico {2019--2020}
\Titolo {Titolo}
\Sottotitolo {Tesi in \ldots }
\Candidato [MATRICOLA123456]{Niccolò~Maltoni}
\NCandidato {Presentata da}
\Relatore {Prof.~Tizio~Relatore}
\Correlatore {Prof.~Tizio~Correlatore}
\Piede {III sessione di laurea \\Anno Accademico 2019--2020}
\begin {document}
\preparefrontpagestandard
\end {document}
```

**Comment by NiccoMlt** [comment]
Another solution that may work is the one linked on [Overleaf support](https://it.overleaf.com/learn/latex/Questions/How_do_I_use_the_frontespizio_package%3F):

```latex
\begin{frontespizio} 
\Istituzione{Alma Mater Studiorum --- Università di Bologna \\Campus di Cesena}
% ... your other information here
\end{frontespizio}
\IfFileExists{\jobname-frn.pdf}{}{%
\immediate\write18{lualatex \jobname-frn}}
```

**Comment by NiccoMlt** [comment]
Because these solutions were not working as expected, I asked to Overleaf support what should I do to resolve the problem. Here is what they replied:

> Hi Nicco,
>
> Thanks for getting in touch, and sorry that you are having this issue.
>
> The compile flow for LuaLaTeX is significantly different than the sequence used for pdfLaTeX, LaTeX, and XeLaTeX. 
>
> For your requirements, will switching to XeLaTeX work? I find that changing the compiler to XeLaTeX allows the frontspiece to be compiled and inserted in your document.
>
> > On January 14, 2020, 9:08 AM EST nicco.mlt@gmail.com wrote:
> >
> > Hi,
> > I'm trying to build a simple thesis project which uses frontespizio package to generate frontspiece.
> > Locally on my machine, I can build the output-frn.tex file generated by the package, so following lualatex invocations will load the generated PDF.
> > To automatize it, I use an arara rule.
> > The problem is that on Overleaf arara is not supported and I can't find a way to make Overleaf generate the frontspiece.
> >I've found on https://it.overleaf.com/learn/latex/Questions%2FHow_do_I_use_the_frontespizio_package%3F a solution, but it doesn't work: first page keeps being compiled as blank.
> >
> > How can I solve my problem?

I tried and the suggested solution seems to work. You can do something like this:

1. Replace `lualatex` with `xelatex` from the side menu of Overleaf
2. Add the following code in `frontespizio.tex` file:
    ```latex
    \begin{frontespizio} 
    \Istituzione{Alma Mater Studiorum --- Università di Bologna \\Campus di Cesena}
        % ... your other information here
    \end{frontespizio}
    \IfFileExists{\jobname-frn.pdf}{}{%
    \immediate\write18{xelatex \jobname-frn}}
    ```

In a following commit, I will address this issue somehow.

**Comment by NiccoMlt** [comment]
I received another mail from Overleaf support:

> Hello Niccolò,
> 
> My colleague, ***, asked me to have a look at your message—happy to help!
>
> LuaLaTeX has now removed \write18 (see https://tex.stackexchange.com/a/366200 for further details), so the \write18 operation on line 196 would not have worked at all when compiling with LuaLaTeX.
>
> The solution is to add \usepackge{shellesc} in your preamble: this makes \write18 available to LuaLaTeX again. We'll also add this info to the help page.
>
> Does that help?

So I think I can fix that: I'll open a pull request later today.
